// Copyright (c) East-Tec <https://www.east-tec.com/>. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
//
// Flutter icons CustomIcons
// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
// This font was generated by FlutterIcon.com, which is derived from Fontello.

/// The custom icons used in the app.
library;

import 'package:flutter/widgets.dart';

const _kFontFam = 'CustomIcons';
const String? _kFontPkg = null;

/// The East-Tec logo mark.
const IconData eastTecLogoMark = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
